apiVersion: v1
kind: Pod
metadata:
  name: localhost-seccomp-profile
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/relaxed-profile.json # Profile from local node /var/lib/kubelet/seccomp
  containers:
  - name: nginx
    image: nginx
----
apiVersion: v1
kind: Pod
metadata:
  name: runtime-default-profile
spec:
  securityContext:
    seccompProfile:
      type: RunTimeDefault # Container runtime default profile
  containers:
  - name: nginx
    image: nginx